### ISSUE TITLE
Receiver naming in record should be consistent

### ISSUE THREAD

**Issue by swopl** [magley/nakevaleng#18]
Looking at record-typed branch
When naming the receiver stick to a standardized scheme. What I mean is don't sometimes use this to refer to the receiver and then sometimes rec like in record.go. Just so it is always obvious what it is referring to. I'd suggest sticking to rec since that way is more go-like and calling it this might cause confusion in people making them not realize that this is not necessarily a pointer to an object: it's just syntax sugar for regular functions.

**Comment by magley** [comment]
Will be fixed (changes are [here](https://github.com/magley/nakevaleng/blob/record-types/core/record/record.go)) on merge.
