### ISSUE TITLE
User of Record can't serialize records in buffered mode

### ISSUE THREAD

**Issue by swopl** [magley/nakevaleng#19]
Looking at record-typed branch:
The exported Serialize in the record package doesn't allow the users to use buffered writing for writing the record objects. It uses buffered writers to writer, but immediately flushes the newly created writer, defeating the purpose of buffered writing.
The currently unexported serialize should probably be exported instead of this, so users can flush their writer whenever. Even WAL should be able to use the Record like this for itself (if buffered writing is what we're going for over there)

**Comment by magley** [comment]
Fixed, all `Serialize()` methods accept only a buffered writer now.
