### ISSUE TITLE
Each user gets a token bucket

### ISSUE THREAD

**Issue by magley** [magley/nakevaleng#25]
As per project specification, the token buckets should be assigned to user each. There's two ways of doing this:
(A): TokenBucket is actually a map from strings (usernames) to individual token buckets.

(B): Integrate the buckets into the key-value system.
1) Create `ToBytes()` and `FromBytes()` for the `TokenBucket` struct.
2) Create `core/tokenbucketdriver` which has the following interface:
2.1) `makeKey(user string)` which maps a username to a unique key like `"user"` -> `"?__user"`
2.2) `HasEnoughTokens(user string, data *Skiplist)`
2.3) `RegisterUser(user string, data *Skiplist)`

(A) is easier and more sound but are we allowed to do it like that?

**Comment by swopl** [comment]
How about this way:
Usernames are automatically registered upon failing to GET their Token Bucket in a system, Very simple to implement instead of making a driver. Thoughts?
